"""Rebuild the static hero from surveyed map geometry; never move geographic points.

Road/area shapes: OSM (ODbL), with source and snapshot date in the JSON.
POIs: building geometry or address coordinates, each with its own source URL.
Only text labels have presentation offsets. North is up; both axes share a scale.
"""
import html
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'assets/location-map-data.json').read_text())
p = data['projection']

def project(point):
    lon, lat = point
    return (380 + (lon - p['centerLon']) * p['latitudeScale'] * math.cos(math.radians(p['referenceLat'])),
            75 + (p['northLat'] - lat) * p['latitudeScale'])

def shape(points):
    return 'M' + ' L'.join(f'{x:.1f} {y:.1f}' for x, y in map(project, points))

def escape(value):
    return html.escape(str(value), quote=True)

out = ['''      <!-- LOCATION MAP: generated by scripts/build-location-map.py from actual WGS84 geometry. -->
      <svg class="location-map" viewBox="0 0 760 710" role="img" aria-labelledby="location-map-title location-map-desc" xmlns="http://www.w3.org/2000/svg">
        <title id="location-map-title">충북혁신도시 내 더나은 본사와 공공기관 위치</title>
        <desc id="location-map-desc">북쪽이 위인 실제 도로 기반 지도. 본사, 터미널과 14개 공공기관을 건물 좌표에 표시했습니다. 안내선은 기관 이름을 연결하며 이동 경로가 아닙니다.</desc>
        <defs>
          <clipPath id="location-map-clip"><rect x="8" y="8" width="744" height="694" rx="30"/></clipPath>
          <radialGradient id="location-hq-glow"><stop stop-color="#ff9c58" stop-opacity=".22"/><stop offset="1" stop-color="#ff9c58" stop-opacity="0"/></radialGradient>
        </defs>
        <g clip-path="url(#location-map-clip)">
          <rect x="8" y="8" width="744" height="694" fill="#f5f6f1"/>''']
for kind, color in [('green','#e7ecdf'),('water','#dce9e9'),('building','#e4e8e2')]:
    paths=[]
    for f in data['features']:
        if f['kind']==kind:
            paths.append(shape(f['coordinates'])+' Z')
    out.append(f'          <path fill="{color}" d="{" ".join(paths)}"/>')
roads = [f for f in data['features'] if f['kind']=='road']
for major in [False, True]:
    subset=[f for f in roads if (f['highway'] in ('trunk','trunk_link','primary','secondary','tertiary','tertiary_link'))==major]
    paths=' '.join(shape(f['coordinates']) for f in subset)
    out.append(f'          <g fill="none" stroke="#d2dbd3" stroke-width="{6.8 if major else 3.5}" stroke-linecap="round" stroke-linejoin="round"><path id="location-roads-{int(major)}" d="{paths}"/></g>')
    out.append(f'          <use href="#location-roads-{int(major)}" fill="none" stroke="#fffef9" stroke-width="{4.9 if major else 2.3}" stroke-linecap="round" stroke-linejoin="round"/>')
# Label named roads at a measured point on the original way, not a made-up stroke.
for name, way, index, angle in [('원중로','679992893',30,0),('용두로','565370558',7,34),('정통로','480626024',0,32),('교학로','547113085',1,27),('두레로','480116646',35,0)]:
    f=next(f for f in roads if f['id']==way)
    x,y=project(f['coordinates'][index])
    out.append(f'          <text class="location-map__road-label" transform="translate({x:.1f} {y-6:.1f}) rotate({angle})">{name}</text>')
out.append('        </g>')
out.append('''        <g class="location-map__heading">
          <rect x="26" y="25" width="202" height="76" rx="16" fill="#f9faf6" fill-opacity=".95"/>
          <text x="44" y="52" fill="#83908c" font-size="10" letter-spacing="1.3" font-family="JetBrains Mono,monospace">OUR NEIGHBORHOOD</text>
          <text x="43" y="81" fill="#35464c" font-size="23" font-weight="600" letter-spacing="-.8">충북혁신도시</text>
        </g>
        <g transform="translate(707 49)" fill="#70827b" text-anchor="middle">
          <circle cy="9" r="27" fill="#f9faf6" fill-opacity=".9"/>
          <text y="2" font-size="12" font-family="JetBrains Mono,monospace">N</text>
          <path d="M0 10 L-5 25 L0 22 L5 25 Z"/>
        </g>''')
for num, item in enumerate(data['places'],1):
    x,y=project(item['coordinates']); lx,ly,anchor=item['label'];kind=item['kind']
    out.append(f'        <g class="location-map__place location-map__place--{kind}" data-place="{escape(item["name"])}" data-lng="{item["coordinates"][0]}" data-lat="{item["coordinates"][1]}">')
    out.append(f'          <title>{escape(item["name"])} · {escape(item["address"])}</title>')
    if kind=='hq':
        out.append(f'''          <circle cx="{x:.1f}" cy="{y:.1f}" r="50" fill="url(#location-hq-glow)"/>
          <circle cx="{x:.1f}" cy="{y:.1f}" r="13" fill="#f78947" stroke="#fff" stroke-width="5"/>
          <circle cx="{x:.1f}" cy="{y:.1f}" r="23" fill="none" stroke="#f78947" stroke-opacity=".28"/>
          <path d="M{x+18:.1f} {y:.1f} H{lx-6}" stroke="#efa778" fill="none"/>
          <g class="location-map__hq-label" transform="translate({lx} {ly})">
            <rect x="-12" y="-20" width="192" height="53" rx="11" fill="#fff" stroke="#f1ccb2"/>
            <text y="0" fill="#35434a" font-size="21" font-weight="700">(주)더나은 본사</text>
            <text y="21" fill="#897867" font-size="13">경동스마트밸리 206호</text>
          </g>''')
    else:
        tx=lx-7 if anchor=='start' else lx+7
        out.append(f'          <path class="location-map__leader" d="M{x:.1f} {y:.1f} L{tx} {ly-5}"/>')
        out.append(f'          <circle class="location-map__node" cx="{x:.1f}" cy="{y:.1f}" r="6"/>')
        out.append(f'          <text class="location-map__number" x="{x:.1f}" y="{y+5.6:.1f}" text-anchor="middle">{num:02d}</text>')
        out.append(f'          <text class="location-map__label" x="{lx}" y="{ly}" text-anchor="{anchor}">')
        for i,line in enumerate(item['lines']):
            out.append(f'            <tspan x="{lx}" dy="{0 if i==0 else 19}">{escape(line)}</tspan>')
        out.append('          </text>')
    out.append('        </g>')
# 500m at the same linear geographic scale as the map.
scale=500/111320*p['latitudeScale']
out.append(f'''        <g transform="translate(45 666)" class="location-map__scale">
          <rect x="-13" y="-28" width="{scale+28:.1f}" height="47" rx="8" fill="#f9faf6" fill-opacity=".95"/>
          <path d="M0 -5 V0 H{scale:.1f} V-5" fill="none" stroke="#809187" stroke-width="1.5"/>
          <text x="{scale/2:.1f}" y="-10" text-anchor="middle" fill="#728179" font-size="12">500 m</text>
        </g>
      </svg>
      <div class="location-map__caption"><span>충북혁신도시 · 주요 공공기관</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a></div>
      <ol class="location-map__key" aria-label="지도에 표시된 공공기관과 터미널">''')
for i,item in enumerate(data['places'][:-1],1):
    out.append(f'        <li><span>{i:02d}</span>{escape(item["name"])}</li>')
out.append('      </ol>\n      <!-- /LOCATION MAP -->')
page=ROOT/'location.html'; text=page.read_text()
start=text.index('      <!-- LOCATION MAP:') if '<!-- LOCATION MAP:' in text else text.index('      <svg class="location-map"')
end=text.index('      <!-- /LOCATION MAP -->',start)+len('      <!-- /LOCATION MAP -->') if '<!-- /LOCATION MAP -->' in text else text.index('      </svg>',start)+len('      </svg>')
page.write_text(text[:start]+'\n'.join(out)+text[end:])
print(f'Generated {len(roads)} road ways and {len(data["places"])} georeferenced places.')
